### ISSUE TITLE
Closed classes

### ISSUE THREAD

**Issue by Thrameos** [Thrameos/jpype#3]
Currently calling a setattr on a java object can succeed even if there is nothing on the java side to support the call.  This has been found to a be a source of bugs in our development.   A static member variable may be exposed and set in the python code.  Later we remove that static.  As the python code silently accepts this setting, we end up not seeing the problem or worse think that the action has the desired effect.  We have patched the base class with a customizer, but depending on the order that classes are constructed it is not always getting called.   Either customizers need to be enhanced to work on classes later, or we need to get this change pushed to the jpype base.  How much code this will break remains to be seen.

**Comment by Thrameos** [comment]
Before:
```python
>>> s=java.lang.String('foo')
>>> s.a=1
>>> s.a
1
```

After:
```python
>>> s=java.lang.String('foo')
>>> s.a=1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nelson85/open/jpype/jpype/_jclass.py", line 105, in _javaSetAttr
    or isinstance(getattr(self.__class__, attr), property):
AttributeError: type object 'java.lang.String' has no attribute 'a'
```
